""" Simple HTTP request handler based on Python SimpleHTTPServer """

#!/usr/bin/env python
import SimpleHTTPServer
# The SimpleHTTPServer module has been merged into http.server in Python 3.
import SocketServer

class MyRequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler, object):
    """ --- """
    # class SimpleHTTPServer.SimpleHTTPRequestHandler(request, client_address, server)
    # This class serves files from the current directory and below,
    # directly mapping the directory structure to HTTP requests.

    def __init__(self):
        """ Inherit the __init__ method from parent class """
        # to disable the Pylint message "Missing argument to super()
        # (missing-super-argument)" just add:
        #   either \pound-sign\ pylint: disable=E1004
        #   or     \pound-sign\ pylint: disable=missing-super-argument
        # at the beginning of the file. If not the workaround below works.
        # Parent class is: SimpleHTTPServer.SimpleHTTPRequestHandler
        # Inheritance is possible from objects, mentionned AFTER old-style
        # class to be inherited from, so the 'object''s methods aren't
        # found first. Inheriting from 'object' gives a new-style class,
        # MyRequestHandler, which works with super().
        super(MyRequestHandler, self).__init__()
        self.path = ""

    def do_GET(self):
        """ --- """
        if self.path == '/':
            self.path = '/ourService.html'
        return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)
        # do_GET() request mapped to local file by interpreting request
        # as path relative to the current working directory.
        # If request was mapped to directory, directory is checked for
        # file named index.html or index.htm (in that order). If found,
        # file\'s contents are returned; otherwise a directory listing is
        # generated by calling the list_directory() method. This method
        # uses os.listdir() to scan the directory, and returns a 404 error
        # response if the listdir() fails.

HANDLER = MyRequestHandler()
SERVER = SocketServer.TCPServer(('0.0.0.0', 8954), HANDLER)

print 'Started my REST API on port 8954'
SERVER.serve_forever()
